"""initial finance core

Revision ID: 8857af05ac59
Revises:
Create Date: 2026-05-01 10:45:28.817631

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "8857af05ac59"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financial_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_financial_categories_slug"), ["slug"], unique=True)

    op.create_table(
        "financial_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum(
                "RECEITA",
                "DESPESA",
                "REPASSE",
                "AJUSTE",
                name="entry_type_enum",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("competence_month", sa.String(length=7), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column(
            "service_area",
            sa.Enum(
                "RI",
                "RC",
                "NOTAS",
                "PROTESTO",
                "RTD",
                "GERAL",
                name="service_area_enum",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAID",
                "RECEIVED",
                "CANCELLED",
                "TO_REVIEW",
                name="entry_status_enum",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "competence_month GLOB '[0-9][0-9][0-9][0-9]-[0-1][0-9]'",
            name="ck_financial_entries_competence_month_format",
        ),
        sa.CheckConstraint("amount > 0", name="ck_financial_entries_amount_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financial_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_financial_entries_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_financial_entries_competence_month"), ["competence_month"], unique=False
        )
        batch_op.create_index(
            "ix_financial_entries_competence_type", ["competence_month", "entry_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_financial_entries_entry_type"), ["entry_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_financial_entries_service_area"), ["service_area"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_financial_entries_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("financial_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financial_entries_status"))
        batch_op.drop_index(batch_op.f("ix_financial_entries_service_area"))
        batch_op.drop_index(batch_op.f("ix_financial_entries_entry_type"))
        batch_op.drop_index("ix_financial_entries_competence_type")
        batch_op.drop_index(batch_op.f("ix_financial_entries_competence_month"))
        batch_op.drop_index(batch_op.f("ix_financial_entries_category"))

    op.drop_table("financial_entries")
    with op.batch_alter_table("financial_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financial_categories_slug"))

    op.drop_table("financial_categories")
    # ### end Alembic commands ###
